-- 1
SELECT NomA, PrenomA FROM ADHERENT WHERE VilleA = 'Paris';
-- 2
SELECT DestinationV, DureeV, CoutV, TypeV
FROM Voyage
WHERE (TypeV = 'RD' OR TypeV = 'SD')
AND CoutV <= 15000;

-- 11
SELECT TypeV, avg(CoutV) FROM VOYAGE WHERE DureeV = 1;

-- 12
SELECT RefV, DestinationV, count(DEPART.*) 
FROM VOYAGE NATURAL JOIN DEPART
WHERE TypeV = 'CT'; 
GROUP BY RefV

-- 13
SELECT count(*) FROM VOYAGE GROUP BY DestinationV, TypeV;

-- 14
SELECT DestinationV, max(CoutV), min(CoutV), avg(CoutV) 
FROM VOYAGE 
WHERE DureeV = 2
GROUP BY DestinationV

-- 15
SELECT count(RESERVATION.*), sum(Acompte), avg(Acompte)
FROM RESERVATION
GROUP BY RefV

-- 25
SELECT NomA, PrenomA, VilleA
FROM ADHERENT
WHERE NomA = 'AL%';

-- 26
SELECT NomA, PrenomA, VilleA
FROM ADHERENT
WHERE NomA LIKE 'AL%' OR NomA LIKE 'LA%';

-- 27
SELECT NomA, PrenomA, NumA, RefV, DateDepart
FROM ADHERENT
NATURAL JOIN RESERVATION
WHERE NomA LIKE '%ON';

--36
SELECT NomA, PrenomA, RefV, DateDepart, (CoutV - Acompte)
FROM ADHERENT
NATURAL JOIN RESERVATION
NATURAL JOIN VOYAGE;

-- 37
SELECT * 
FROM VOYAGE
WHERE CoutV < (
	SELECT avg(CoutV) from VOYAGE WHERE TypeV = 'SD' 
);

-- 38
SELECT ADHERENT.*
FROM ADHERENT
NATURAL JOIN RESERVATION
NATURAL JOIN VOYAGE
WHERE CoutV < (
	SELECT avg(CoutV) FROM VOYAGE WHERE TypeV = 'SD' 
);

-- 39
SELECT *
FROM VOYAGE
WHERE CoutV < (
	SELECT min(CoutV) FROM VOYAGE WHERE DureeV = 3
);

-- 40
SELECT ADHERENT.*
FROM ADHERENT
NATURAL JOIN RESERVATION
NATURAL JOIN VOYAGE
WHERE CoutV > (
	SELECT avg(CoutV) FROM VOYAGE
) * 1.25;

-- 41
SELECT ADHERENT.*
FROM ADHERENT
WHERE NumA NOT IN (
	SELECT NumA FROM RESERVATION
);

-- 42
SELECT ADHERENT.*
FROM ADHERENT
WHERE NumA NOT IN (
	SELECT NumA FROM RESERVATION
	NATURAL JOIN VOYAGE
	WHERE TypeV = 'CT'
);

-- 43
SELECT NumA 
FROM RESERVATION
NATURAL JOIN VOYAGE
WHERE 
	(DestinationV = 'Tunisie' AND TypeV = 'RD')
	AND
	(DestinationV = 'Italie' AND TypeV = 'SP');

-- 44

